# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Markit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!



  target 'MarkitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarkitUITests' do
    # Pods for testing
  end
pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON'
pod 'MaterialComponents/TextControls+FilledTextAreas'
pod 'MaterialComponents/TextControls+FilledTextFields'
pod 'MaterialComponents/TextControls+OutlinedTextAreas'
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'PINRemoteImage'

end
